apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  template:
    metadata:
      name: transaction-service
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: goceefake/transaction-service
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local-microservice
      restartPolicy: Always
  selector:
    matchLabels:
      app: transaction-service

---

apiVersion: v1
kind: Service
metadata:
  name: bankapp-transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - port: 8082
      nodePort: 30040
  type: NodePort